n = int(input())
if n > 100: print("Error : Value must be less than or equal to 100.")
elif n < 0: print("Error : Value must be greater than or equal to 0.")
elif n < 60: print("F")
elif n in range (60,65): print("D")
elif n in range (65,70): print("D+")
elif n in range (70,75): print("C")
elif n in range (75,80): print("C+")
elif n in range (80,85): print("B")
elif n in range (85,90): print("B+")
else: print("A")